# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/AssetDigestEntry.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.AssetDigestEntry" do
    optional :asset_id, :string, 1
    optional :bundle_name, :string, 2
    optional :version, :int64, 3
    optional :checksum, :fixed32, 4
    optional :size, :int32, 5
    optional :key, :bytes, 6
  end
end

module POGOProtos
  module Data
    AssetDigestEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.AssetDigestEntry").msgclass
  end
end
