# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/PlayerData.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/TutorialState'
require 'poke-api/POGOProtos/Data/Player/PlayerAvatar'
require 'poke-api/POGOProtos/Data/Player/DailyBonus'
require 'poke-api/POGOProtos/Data/Player/EquippedBadge'
require 'poke-api/POGOProtos/Data/Player/ContactSettings'
require 'poke-api/POGOProtos/Data/Player/Currency'
require 'poke-api/POGOProtos/Enums/TeamColor'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.PlayerData" do
    optional :creation_timestamp_ms, :int64, 1
    optional :username, :string, 2
    optional :team, :enum, 5, "POGOProtos.Enums.TeamColor"
    repeated :tutorial_state, :enum, 7, "POGOProtos.Enums.TutorialState"
    optional :avatar, :message, 8, "POGOProtos.Data.Player.PlayerAvatar"
    optional :max_pokemon_storage, :int32, 9
    optional :max_item_storage, :int32, 10
    optional :daily_bonus, :message, 11, "POGOProtos.Data.Player.DailyBonus"
    optional :equipped_badge, :message, 12, "POGOProtos.Data.Player.EquippedBadge"
    optional :contact_settings, :message, 13, "POGOProtos.Data.Player.ContactSettings"
    repeated :currencies, :message, 14, "POGOProtos.Data.Player.Currency"
  end
end

module POGOProtos
  module Data
    PlayerData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PlayerData").msgclass
  end
end
