# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/MapObjectsStatus.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Map.MapObjectsStatus" do
    value :UNSET_STATUS, 0
    value :SUCCESS, 1
    value :LOCATION_UNSET, 2
  end
end

module POGOProtos
  module Map
    MapObjectsStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.MapObjectsStatus").enummodule
  end
end
