# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/SpawnPoint.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.SpawnPoint" do
    optional :latitude, :double, 2
    optional :longitude, :double, 3
  end
end

module POGOProtos
  module Map
    SpawnPoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.SpawnPoint").msgclass
  end
end
