# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/MapSettings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.MapSettings" do
    optional :pokemon_visible_range, :double, 1
    optional :poke_nav_range_meters, :double, 2
    optional :encounter_range_meters, :double, 3
    optional :get_map_objects_min_refresh_seconds, :float, 4
    optional :get_map_objects_max_refresh_seconds, :float, 5
    optional :get_map_objects_min_distance_meters, :float, 6
    optional :google_maps_api_key, :string, 7
  end
end

module POGOProtos
  module Settings
    MapSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.MapSettings").msgclass
  end
end
