# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CheckCodenameAvailableResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.CheckCodenameAvailableResponse" do
    optional :codename, :string, 1
    optional :user_message, :string, 2
    optional :is_assignable, :bool, 3
    optional :status, :enum, 4, "POGOProtos.Networking.Responses.CheckCodenameAvailableResponse.Status"
  end
  add_enum "POGOProtos.Networking.Responses.CheckCodenameAvailableResponse.Status" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :CODENAME_NOT_AVAILABLE, 2
    value :CODENAME_NOT_VALID, 3
    value :CURRENT_OWNER, 4
    value :CODENAME_CHANGE_NOT_ALLOWED, 5
  end
end

module POGOProtos
  module Networking
    module Responses
      CheckCodenameAvailableResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CheckCodenameAvailableResponse").msgclass
      CheckCodenameAvailableResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CheckCodenameAvailableResponse.Status").enummodule
    end
  end
end
