# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CheckAwardedBadgesResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/BadgeType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.CheckAwardedBadgesResponse" do
    optional :success, :bool, 1
    repeated :awarded_badges, :enum, 2, "POGOProtos.Enums.BadgeType"
    repeated :awarded_badge_levels, :int32, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      CheckAwardedBadgesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CheckAwardedBadgesResponse").msgclass
    end
  end
end
