# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CollectDailyDefenderBonusResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.CollectDailyDefenderBonusResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.CollectDailyDefenderBonusResponse.Result"
    repeated :currency_type, :string, 2
    repeated :currency_awarded, :int32, 3
    optional :defenders_count, :int32, 4
  end
  add_enum "POGOProtos.Networking.Responses.CollectDailyDefenderBonusResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :FAILURE, 2
    value :TOO_SOON, 3
    value :NO_DEFENDERS, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      CollectDailyDefenderBonusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CollectDailyDefenderBonusResponse").msgclass
      CollectDailyDefenderBonusResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CollectDailyDefenderBonusResponse.Result").enummodule
    end
  end
end
