# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CollectDailyBonusResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.CollectDailyBonusResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.CollectDailyBonusResponse.Result"
  end
  add_enum "POGOProtos.Networking.Responses.CollectDailyBonusResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :FAILURE, 2
    value :TOO_SOON, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      CollectDailyBonusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CollectDailyBonusResponse").msgclass
      CollectDailyBonusResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.CollectDailyBonusResponse.Result").enummodule
    end
  end
end
