# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/DiskEncounterResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/PokemonData'
require 'poke-api/POGOProtos/Data/Capture/CaptureProbability'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.DiskEncounterResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.DiskEncounterResponse.Result"
    optional :pokemon_data, :message, 2, "POGOProtos.Data.PokemonData"
    optional :capture_probability, :message, 3, "POGOProtos.Data.Capture.CaptureProbability"
  end
  add_enum "POGOProtos.Networking.Responses.DiskEncounterResponse.Result" do
    value :UNKNOWN, 0
    value :SUCCESS, 1
    value :NOT_AVAILABLE, 2
    value :NOT_IN_RANGE, 3
    value :ENCOUNTER_ALREADY_FINISHED, 4
    value :POKEMON_INVENTORY_FULL, 5
  end
end

module POGOProtos
  module Networking
    module Responses
      DiskEncounterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.DiskEncounterResponse").msgclass
      DiskEncounterResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.DiskEncounterResponse.Result").enummodule
    end
  end
end
