# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/EchoResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.EchoResponse" do
    optional :context, :string, 1
  end
end

module POGOProtos
  module Networking
    module Responses
      EchoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EchoResponse").msgclass
    end
  end
end
