# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/EncounterResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Capture/CaptureProbability'
require 'poke-api/POGOProtos/Map/Pokemon/WildPokemon'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.EncounterResponse" do
    optional :wild_pokemon, :message, 1, "POGOProtos.Map.Pokemon.WildPokemon"
    optional :background, :enum, 2, "POGOProtos.Networking.Responses.EncounterResponse.Background"
    optional :status, :enum, 3, "POGOProtos.Networking.Responses.EncounterResponse.Status"
    optional :capture_probability, :message, 4, "POGOProtos.Data.Capture.CaptureProbability"
  end
  add_enum "POGOProtos.Networking.Responses.EncounterResponse.Background" do
    value :PARK, 0
    value :DESERT, 1
  end
  add_enum "POGOProtos.Networking.Responses.EncounterResponse.Status" do
    value :ENCOUNTER_ERROR, 0
    value :ENCOUNTER_SUCCESS, 1
    value :ENCOUNTER_NOT_FOUND, 2
    value :ENCOUNTER_CLOSED, 3
    value :ENCOUNTER_POKEMON_FLED, 4
    value :ENCOUNTER_NOT_IN_RANGE, 5
    value :ENCOUNTER_ALREADY_HAPPENED, 6
    value :POKEMON_INVENTORY_FULL, 7
  end
end

module POGOProtos
  module Networking
    module Responses
      EncounterResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EncounterResponse").msgclass
      EncounterResponse::Background = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EncounterResponse.Background").enummodule
      EncounterResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EncounterResponse.Status").enummodule
    end
  end
end
