# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/EquipBadgeResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Player/EquippedBadge'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.EquipBadgeResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.EquipBadgeResponse.Result"
    optional :equipped, :message, 2, "POGOProtos.Data.Player.EquippedBadge"
  end
  add_enum "POGOProtos.Networking.Responses.EquipBadgeResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :COOLDOWN_ACTIVE, 2
    value :NOT_QUALIFIED, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      EquipBadgeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EquipBadgeResponse").msgclass
      EquipBadgeResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.EquipBadgeResponse.Result").enummodule
    end
  end
end
