# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/FortRecallPokemonResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Networking/Responses/FortDetailsResponse'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.FortRecallPokemonResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.FortRecallPokemonResponse.Result"
    optional :fort_details, :message, 2, "POGOProtos.Networking.Responses.FortDetailsResponse"
  end
  add_enum "POGOProtos.Networking.Responses.FortRecallPokemonResponse.Result" do
    value :NO_RESULT_SET, 0
    value :SUCCESS, 1
    value :ERROR_NOT_IN_RANGE, 2
    value :ERROR_POKEMON_NOT_ON_FORT, 3
    value :ERROR_NO_PLAYER, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      FortRecallPokemonResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.FortRecallPokemonResponse").msgclass
      FortRecallPokemonResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.FortRecallPokemonResponse.Result").enummodule
    end
  end
end
