# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/FortDetailsResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/PokemonData'
require 'poke-api/POGOProtos/Enums/TeamColor'
require 'poke-api/POGOProtos/Map/Fort/FortType'
require 'poke-api/POGOProtos/Map/Fort/FortModifier'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.FortDetailsResponse" do
    optional :fort_id, :string, 1
    optional :team_color, :enum, 2, "POGOProtos.Enums.TeamColor"
    optional :pokemon_data, :message, 3, "POGOProtos.Data.PokemonData"
    optional :name, :string, 4
    repeated :image_urls, :string, 5
    optional :fp, :int32, 6
    optional :stamina, :int32, 7
    optional :max_stamina, :int32, 8
    optional :type, :enum, 9, "POGOProtos.Map.Fort.FortType"
    optional :latitude, :double, 10
    optional :longitude, :double, 11
    optional :description, :string, 12
    repeated :modifiers, :message, 13, "POGOProtos.Map.Fort.FortModifier"
  end
end

module POGOProtos
  module Networking
    module Responses
      FortDetailsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.FortDetailsResponse").msgclass
    end
  end
end
