# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetAssetDigestResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/AssetDigestEntry'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetAssetDigestResponse" do
    repeated :digest, :message, 1, "POGOProtos.Data.AssetDigestEntry"
    optional :timestamp_ms, :uint64, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      GetAssetDigestResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetAssetDigestResponse").msgclass
    end
  end
end
