# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetDownloadUrlsResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/DownloadUrlEntry'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetDownloadUrlsResponse" do
    repeated :download_urls, :message, 1, "POGOProtos.Data.DownloadUrlEntry"
  end
end

module POGOProtos
  module Networking
    module Responses
      GetDownloadUrlsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetDownloadUrlsResponse").msgclass
    end
  end
end
