# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetIncensePokemonResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetIncensePokemonResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.GetIncensePokemonResponse.Result"
    optional :pokemon_id, :enum, 2, "POGOProtos.Enums.PokemonId"
    optional :latitude, :double, 3
    optional :longitude, :double, 4
    optional :encounter_location, :string, 5
    optional :encounter_id, :fixed64, 6
    optional :disappear_timestamp_ms, :int64, 7
  end
  add_enum "POGOProtos.Networking.Responses.GetIncensePokemonResponse.Result" do
    value :INCENSE_ENCOUNTER_UNKNOWN, 0
    value :INCENSE_ENCOUNTER_AVAILABLE, 1
    value :INCENSE_ENCOUNTER_NOT_AVAILABLE, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      GetIncensePokemonResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetIncensePokemonResponse").msgclass
      GetIncensePokemonResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetIncensePokemonResponse.Result").enummodule
    end
  end
end
