# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetMapObjectsResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Map/MapCell'
require 'poke-api/POGOProtos/Map/MapObjectsStatus'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetMapObjectsResponse" do
    repeated :map_cells, :message, 1, "POGOProtos.Map.MapCell"
    optional :status, :enum, 2, "POGOProtos.Map.MapObjectsStatus"
  end
end

module POGOProtos
  module Networking
    module Responses
      GetMapObjectsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetMapObjectsResponse").msgclass
    end
  end
end
