# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetPlayerResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/PlayerData'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetPlayerResponse" do
    optional :success, :bool, 1
    optional :player_data, :message, 2, "POGOProtos.Data.PlayerData"
  end
end

module POGOProtos
  module Networking
    module Responses
      GetPlayerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetPlayerResponse").msgclass
    end
  end
end
