# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetSuggestedCodenamesResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.GetSuggestedCodenamesResponse" do
    repeated :codenames, :string, 1
    optional :success, :bool, 2
  end
end

module POGOProtos
  module Networking
    module Responses
      GetSuggestedCodenamesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.GetSuggestedCodenamesResponse").msgclass
    end
  end
end
