# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/NicknamePokemonResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.NicknamePokemonResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.NicknamePokemonResponse.Result"
  end
  add_enum "POGOProtos.Networking.Responses.NicknamePokemonResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :ERROR_INVALID_NICKNAME, 2
    value :ERROR_POKEMON_NOT_FOUND, 3
    value :ERROR_POKEMON_IS_EGG, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      NicknamePokemonResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.NicknamePokemonResponse").msgclass
      NicknamePokemonResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.NicknamePokemonResponse.Result").enummodule
    end
  end
end
