# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/PlayerUpdateResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Map/Fort/FortData'
require 'poke-api/POGOProtos/Map/Pokemon/WildPokemon'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.PlayerUpdateResponse" do
    repeated :wild_pokemons, :message, 1, "POGOProtos.Map.Pokemon.WildPokemon"
    repeated :forts, :message, 2, "POGOProtos.Map.Fort.FortData"
    optional :forts_nearby, :int32, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      PlayerUpdateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.PlayerUpdateResponse").msgclass
    end
  end
end
