# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetAvatarResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/PlayerData'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.SetAvatarResponse" do
    optional :status, :enum, 1, "POGOProtos.Networking.Responses.SetAvatarResponse.Status"
    optional :player_data, :message, 2, "POGOProtos.Data.PlayerData"
  end
  add_enum "POGOProtos.Networking.Responses.SetAvatarResponse.Status" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :AVATAR_ALREADY_SET, 2
    value :FAILURE, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      SetAvatarResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetAvatarResponse").msgclass
      SetAvatarResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetAvatarResponse.Status").enummodule
    end
  end
end
