# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetPlayerTeamResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/PlayerData'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.SetPlayerTeamResponse" do
    optional :status, :enum, 1, "POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status"
    optional :player_data, :message, 2, "POGOProtos.Data.PlayerData"
  end
  add_enum "POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :TEAM_ALREADY_SET, 2
    value :FAILURE, 3
  end
end

module POGOProtos
  module Networking
    module Responses
      SetPlayerTeamResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetPlayerTeamResponse").msgclass
      SetPlayerTeamResponse::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status").enummodule
    end
  end
end
