# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseIncenseResponse.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/AppliedItem'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.UseIncenseResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.UseIncenseResponse.Result"
    optional :applied_incense, :message, 2, "POGOProtos.Inventory.AppliedItem"
  end
  add_enum "POGOProtos.Networking.Responses.UseIncenseResponse.Result" do
    value :UNKNOWN, 0
    value :SUCCESS, 1
    value :INCENSE_ALREADY_ACTIVE, 2
    value :NONE_IN_INVENTORY, 3
    value :LOCATION_UNSET, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      UseIncenseResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseIncenseResponse").msgclass
      UseIncenseResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseIncenseResponse.Result").enummodule
    end
  end
end
