# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseItemPotionResponse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Responses.UseItemPotionResponse" do
    optional :result, :enum, 1, "POGOProtos.Networking.Responses.UseItemPotionResponse.Result"
    optional :stamina, :int32, 2
  end
  add_enum "POGOProtos.Networking.Responses.UseItemPotionResponse.Result" do
    value :UNSET, 0
    value :SUCCESS, 1
    value :ERROR_NO_POKEMON, 2
    value :ERROR_CANNOT_USE, 3
    value :ERROR_DEPLOYED_TO_FORT, 4
  end
end

module POGOProtos
  module Networking
    module Responses
      UseItemPotionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseItemPotionResponse").msgclass
      UseItemPotionResponse::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Responses.UseItemPotionResponse.Result").enummodule
    end
  end
end
