# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Logs/ActionLogEntry.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Logs/CatchPokemonLogEntry'
require 'poke-api/POGOProtos/Data/Logs/FortSearchLogEntry'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Logs.ActionLogEntry" do
    optional :timestamp_ms, :int64, 1
    optional :sfida, :bool, 2
    oneof :Action do
      optional :catch_pokemon, :message, 3, "POGOProtos.Data.Logs.CatchPokemonLogEntry"
      optional :fort_search, :message, 4, "POGOProtos.Data.Logs.FortSearchLogEntry"
    end
  end
end

module POGOProtos
  module Data
    module Logs
      ActionLogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Logs.ActionLogEntry").msgclass
    end
  end
end
