# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Logs/CatchPokemonLogEntry.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Logs.CatchPokemonLogEntry" do
    optional :result, :enum, 1, "POGOProtos.Data.Logs.CatchPokemonLogEntry.Result"
    optional :pokemon_id, :enum, 2, "POGOProtos.Enums.PokemonId"
    optional :combat_points, :int32, 3
    optional :pokemon_data_id, :uint64, 4
  end
  add_enum "POGOProtos.Data.Logs.CatchPokemonLogEntry.Result" do
    value :UNSET, 0
    value :POKEMON_CAPTURED, 1
    value :POKEMON_FLED, 2
  end
end

module POGOProtos
  module Data
    module Logs
      CatchPokemonLogEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Logs.CatchPokemonLogEntry").msgclass
      CatchPokemonLogEntry::Result = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Logs.CatchPokemonLogEntry.Result").enummodule
    end
  end
end
