# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Pokemon/CameraAttributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Pokemon.CameraAttributes" do
    optional :disk_radius_m, :float, 1
    optional :cylinder_radius_m, :float, 2
    optional :cylinder_height_m, :float, 3
    optional :cylinder_ground_m, :float, 4
    optional :shoulder_mode_scale, :float, 5
  end
end

module POGOProtos
  module Settings
    module Master
      module Pokemon
        CameraAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Pokemon.CameraAttributes").msgclass
      end
    end
  end
end
