# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Pokemon/EncounterAttributes.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonMovementType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Pokemon.EncounterAttributes" do
    optional :base_capture_rate, :float, 1
    optional :base_flee_rate, :float, 2
    optional :collision_radius_m, :float, 3
    optional :collision_height_m, :float, 4
    optional :collision_head_radius_m, :float, 5
    optional :movement_type, :enum, 6, "POGOProtos.Enums.PokemonMovementType"
    optional :movement_timer_s, :float, 7
    optional :jump_time_s, :float, 8
    optional :attack_timer_s, :float, 9
  end
end

module POGOProtos
  module Settings
    module Master
      module Pokemon
        EncounterAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Pokemon.EncounterAttributes").msgclass
      end
    end
  end
end
