# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Gym/GymState.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Map/Fort/FortData'
require 'poke-api/POGOProtos/Data/Gym/GymMembership'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Gym.GymState" do
    optional :fort_data, :message, 1, "POGOProtos.Map.Fort.FortData"
    repeated :memberships, :message, 2, "POGOProtos.Data.Gym.GymMembership"
  end
end

module POGOProtos
  module Data
    module Gym
      GymState = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Gym.GymState").msgclass
    end
  end
end
