# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/Item/ItemAward.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/Item/ItemId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.Item.ItemAward" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :item_count, :int32, 2
  end
end

module POGOProtos
  module Inventory
    module Item
      ItemAward = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.Item.ItemAward").msgclass
    end
  end
end
