# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/Item/ItemData.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/Item/ItemId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.Item.ItemData" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :count, :int32, 2
    optional :unseen, :bool, 3
  end
end

module POGOProtos
  module Inventory
    module Item
      ItemData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.Item.ItemData").msgclass
    end
  end
end
