# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Request.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Networking/Requests/RequestType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Request" do
    optional :request_type, :enum, 1, "POGOProtos.Networking.Requests.RequestType"
    optional :request_message, :bytes, 2
  end
end

module POGOProtos
  module Networking
    module Requests
      Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Request").msgclass
    end
  end
end
