# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/BadgeType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.BadgeType" do
    value :BADGE_UNSET, 0
    value :BADGE_TRAVEL_KM, 1
    value :BADGE_POKEDEX_ENTRIES, 2
    value :BADGE_CAPTURE_TOTAL, 3
    value :BADGE_DEFEATED_FORT, 4
    value :BADGE_EVOLVED_TOTAL, 5
    value :BADGE_HATCHED_TOTAL, 6
    value :BADGE_ENCOUNTERED_TOTAL, 7
    value :BADGE_POKESTOPS_VISITED, 8
    value :BADGE_UNIQUE_POKESTOPS, 9
    value :BADGE_POKEBALL_THROWN, 10
    value :BADGE_BIG_MAGIKARP, 11
    value :BADGE_DEPLOYED_TOTAL, 12
    value :BADGE_BATTLE_ATTACK_WON, 13
    value :BADGE_BATTLE_TRAINING_WON, 14
    value :BADGE_BATTLE_DEFEND_WON, 15
    value :BADGE_PRESTIGE_RAISED, 16
    value :BADGE_PRESTIGE_DROPPED, 17
    value :BADGE_TYPE_NORMAL, 18
    value :BADGE_TYPE_FIGHTING, 19
    value :BADGE_TYPE_FLYING, 20
    value :BADGE_TYPE_POISON, 21
    value :BADGE_TYPE_GROUND, 22
    value :BADGE_TYPE_ROCK, 23
    value :BADGE_TYPE_BUG, 24
    value :BADGE_TYPE_GHOST, 25
    value :BADGE_TYPE_STEEL, 26
    value :BADGE_TYPE_FIRE, 27
    value :BADGE_TYPE_WATER, 28
    value :BADGE_TYPE_GRASS, 29
    value :BADGE_TYPE_ELECTRIC, 30
    value :BADGE_TYPE_PSYCHIC, 31
    value :BADGE_TYPE_ICE, 32
    value :BADGE_TYPE_DRAGON, 33
    value :BADGE_TYPE_DARK, 34
    value :BADGE_TYPE_FAIRY, 35
    value :BADGE_SMALL_RATTATA, 36
    value :BADGE_PIKACHU, 37
  end
end

module POGOProtos
  module Enums
    BadgeType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.BadgeType").enummodule
  end
end
