# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/Gender.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.Gender" do
    value :MALE, 0
    value :FEMALE, 1
  end
end

module POGOProtos
  module Enums
    Gender = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.Gender").enummodule
  end
end
