# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/Platform.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.Platform" do
    value :UNSET, 0
    value :IOS, 1
    value :ANDROID, 2
    value :OSX, 3
    value :WINDOWS, 4
  end
end

module POGOProtos
  module Enums
    Platform = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.Platform").enummodule
  end
end
