# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/PokemonFamilyId.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.PokemonFamilyId" do
    value :FAMILY_UNSET, 0
    value :FAMILY_BULBASAUR, 1
    value :FAMILY_CHARMANDER, 4
    value :FAMILY_SQUIRTLE, 7
    value :FAMILY_CATERPIE, 10
    value :FAMILY_WEEDLE, 13
    value :FAMILY_PIDGEY, 16
    value :FAMILY_RATTATA, 19
    value :FAMILY_SPEAROW, 21
    value :FAMILY_EKANS, 23
    value :FAMILY_PIKACHU, 25
    value :FAMILY_SANDSHREW, 27
    value :FAMILY_NIDORAN_FEMALE, 29
    value :FAMILY_NIDORAN_MALE, 32
    value :FAMILY_CLEFAIRY, 35
    value :FAMILY_VULPIX, 37
    value :FAMILY_JIGGLYPUFF, 39
    value :FAMILY_ZUBAT, 41
    value :FAMILY_ODDISH, 43
    value :FAMILY_PARAS, 46
    value :FAMILY_VENONAT, 48
    value :FAMILY_DIGLETT, 50
    value :FAMILY_MEOWTH, 52
    value :FAMILY_PSYDUCK, 54
    value :FAMILY_MANKEY, 56
    value :FAMILY_GROWLITHE, 58
    value :FAMILY_POLIWAG, 60
    value :FAMILY_ABRA, 63
    value :FAMILY_MACHOP, 66
    value :FAMILY_BELLSPROUT, 69
    value :FAMILY_TENTACOOL, 72
    value :FAMILY_GEODUDE, 74
    value :FAMILY_PONYTA, 77
    value :FAMILY_SLOWPOKE, 79
    value :FAMILY_MAGNEMITE, 81
    value :FAMILY_FARFETCHD, 83
    value :FAMILY_DODUO, 84
    value :FAMILY_SEEL, 86
    value :FAMILY_GRIMER, 88
    value :FAMILY_SHELLDER, 90
    value :FAMILY_GASTLY, 92
    value :FAMILY_ONIX, 95
    value :FAMILY_DROWZEE, 96
    value :FAMILY_HYPNO, 97
    value :FAMILY_KRABBY, 98
    value :FAMILY_VOLTORB, 100
    value :FAMILY_EXEGGCUTE, 102
    value :FAMILY_CUBONE, 104
    value :FAMILY_HITMONLEE, 106
    value :FAMILY_HITMONCHAN, 107
    value :FAMILY_LICKITUNG, 108
    value :FAMILY_KOFFING, 109
    value :FAMILY_RHYHORN, 111
    value :FAMILY_CHANSEY, 113
    value :FAMILY_TANGELA, 114
    value :FAMILY_KANGASKHAN, 115
    value :FAMILY_HORSEA, 116
    value :FAMILY_GOLDEEN, 118
    value :FAMILY_STARYU, 120
    value :FAMILY_MR_MIME, 122
    value :FAMILY_SCYTHER, 123
    value :FAMILY_JYNX, 124
    value :FAMILY_ELECTABUZZ, 125
    value :FAMILY_MAGMAR, 126
    value :FAMILY_PINSIR, 127
    value :FAMILY_TAUROS, 128
    value :FAMILY_MAGIKARP, 129
    value :FAMILY_LAPRAS, 131
    value :FAMILY_DITTO, 132
    value :FAMILY_EEVEE, 133
    value :FAMILY_PORYGON, 137
    value :FAMILY_OMANYTE, 138
    value :FAMILY_KABUTO, 140
    value :FAMILY_AERODACTYL, 142
    value :FAMILY_SNORLAX, 143
    value :FAMILY_ARTICUNO, 144
    value :FAMILY_ZAPDOS, 145
    value :FAMILY_MOLTRES, 146
    value :FAMILY_DRATINI, 147
    value :FAMILY_MEWTWO, 150
    value :FAMILY_MEW, 151
  end
end

module POGOProtos
  module Enums
    PokemonFamilyId = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.PokemonFamilyId").enummodule
  end
end
