# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/PokemonType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.PokemonType" do
    value :POKEMON_TYPE_NONE, 0
    value :POKEMON_TYPE_NORMAL, 1
    value :POKEMON_TYPE_FIGHTING, 2
    value :POKEMON_TYPE_FLYING, 3
    value :POKEMON_TYPE_POISON, 4
    value :POKEMON_TYPE_GROUND, 5
    value :POKEMON_TYPE_ROCK, 6
    value :POKEMON_TYPE_BUG, 7
    value :POKEMON_TYPE_GHOST, 8
    value :POKEMON_TYPE_STEEL, 9
    value :POKEMON_TYPE_FIRE, 10
    value :POKEMON_TYPE_WATER, 11
    value :POKEMON_TYPE_GRASS, 12
    value :POKEMON_TYPE_ELECTRIC, 13
    value :POKEMON_TYPE_PSYCHIC, 14
    value :POKEMON_TYPE_ICE, 15
    value :POKEMON_TYPE_DRAGON, 16
    value :POKEMON_TYPE_DARK, 17
    value :POKEMON_TYPE_FAIRY, 18
  end
end

module POGOProtos
  module Enums
    PokemonType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.PokemonType").enummodule
  end
end
