# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/TeamColor.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Enums.TeamColor" do
    value :NEUTRAL, 0
    value :BLUE, 1
    value :RED, 2
    value :YELLOW, 3
  end
end

module POGOProtos
  module Enums
    TeamColor = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Enums.TeamColor").enummodule
  end
end
