# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Pokemon/MapPokemon.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.Pokemon.MapPokemon" do
    optional :spawn_point_id, :string, 1
    optional :encounter_id, :fixed64, 2
    optional :pokemon_id, :enum, 3, "POGOProtos.Enums.PokemonId"
    optional :expiration_timestamp_ms, :int64, 4
    optional :latitude, :double, 5
    optional :longitude, :double, 6
  end
end

module POGOProtos
  module Map
    module Pokemon
      MapPokemon = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Pokemon.MapPokemon").msgclass
    end
  end
end
