# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Pokemon/NearbyPokemon.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.Pokemon.NearbyPokemon" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
    optional :distance_in_meters, :float, 2
    optional :encounter_id, :fixed64, 3
  end
end

module POGOProtos
  module Map
    module Pokemon
      NearbyPokemon = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Pokemon.NearbyPokemon").msgclass
    end
  end
end
