# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/BattleActionType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Data.Battle.BattleActionType" do
    value :ACTION_UNSET, 0
    value :ACTION_ATTACK, 1
    value :ACTION_DODGE, 2
    value :ACTION_SPECIAL_ATTACK, 3
    value :ACTION_SWAP_POKEMON, 4
    value :ACTION_FAINT, 5
    value :ACTION_PLAYER_JOIN, 6
    value :ACTION_PLAYER_QUIT, 7
    value :ACTION_VICTORY, 8
    value :ACTION_DEFEAT, 9
    value :ACTION_TIMED_OUT, 10
  end
end

module POGOProtos
  module Data
    module Battle
      BattleActionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleActionType").enummodule
    end
  end
end
