# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/BattleResults.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Gym/GymState'
require 'poke-api/POGOProtos/Data/Battle/BattleParticipant'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Battle.BattleResults" do
    optional :gym_state, :message, 1, "POGOProtos.Data.Gym.GymState"
    repeated :attackers, :message, 2, "POGOProtos.Data.Battle.BattleParticipant"
    repeated :player_experience_awarded, :int32, 3
    optional :next_defender_pokemon_id, :int64, 4
    optional :gym_points_delta, :int32, 5
  end
end

module POGOProtos
  module Data
    module Battle
      BattleResults = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleResults").msgclass
    end
  end
end
