# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/BattleState.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Data.Battle.BattleState" do
    value :STATE_UNSET, 0
    value :ACTIVE, 1
    value :VICTORY, 2
    value :DEFEATED, 3
    value :TIMED_OUT, 4
  end
end

module POGOProtos
  module Data
    module Battle
      BattleState = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleState").enummodule
    end
  end
end
