# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/BattleType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Data.Battle.BattleType" do
    value :BATTLE_TYPE_UNSET, 0
    value :NORMAL, 1
    value :TRAINING, 2
  end
end

module POGOProtos
  module Data
    module Battle
      BattleType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleType").enummodule
    end
  end
end
