# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/BattleAction.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Battle/BattleResults'
require 'poke-api/POGOProtos/Data/Battle/BattleActionType'
require 'poke-api/POGOProtos/Data/Battle/BattleParticipant'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Battle.BattleAction" do
    optional :Type, :enum, 1, "POGOProtos.Data.Battle.BattleActionType"
    optional :action_start_ms, :int64, 2
    optional :duration_ms, :int32, 3
    optional :energy_delta, :int32, 5
    optional :attacker_index, :int32, 6
    optional :target_index, :int32, 7
    optional :active_pokemon_id, :uint64, 8
    optional :player_joined, :message, 9, "POGOProtos.Data.Battle.BattleParticipant"
    optional :battle_results, :message, 10, "POGOProtos.Data.Battle.BattleResults"
    optional :damage_windows_start_timestamp_mss, :int64, 11
    optional :damage_windows_end_timestamp_mss, :int64, 12
    optional :player_left, :message, 13, "POGOProtos.Data.Battle.BattleParticipant"
    optional :target_pokemon_id, :uint64, 14
  end
end

module POGOProtos
  module Data
    module Battle
      BattleAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleAction").msgclass
    end
  end
end
