# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/BadgeSettings.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/BadgeType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.BadgeSettings" do
    optional :badge_type, :enum, 1, "POGOProtos.Enums.BadgeType"
    optional :badge_rank, :int32, 2
    repeated :targets, :int32, 3
  end
end

module POGOProtos
  module Settings
    module Master
      BadgeSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.BadgeSettings").msgclass
    end
  end
end
