# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/CameraSettings.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/CameraTarget'
require 'poke-api/POGOProtos/Enums/CameraInterpolation'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.CameraSettings" do
    optional :next_camera, :string, 1
    repeated :interpolation, :enum, 2, "POGOProtos.Enums.CameraInterpolation"
    repeated :target_type, :enum, 3, "POGOProtos.Enums.CameraTarget"
    repeated :ease_in_speed, :float, 4
    repeated :east_out_speed, :float, 5
    repeated :duration_seconds, :float, 6
    repeated :wait_seconds, :float, 7
    repeated :transition_seconds, :float, 8
    repeated :angle_degree, :float, 9
    repeated :angle_offset_degree, :float, 10
    repeated :pitch_degree, :float, 11
    repeated :pitch_offset_degree, :float, 12
    repeated :roll_degree, :float, 13
    repeated :distance_meters, :float, 14
    repeated :height_percent, :float, 15
    repeated :vert_ctr_ratio, :float, 16
  end
end

module POGOProtos
  module Settings
    module Master
      CameraSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.CameraSettings").msgclass
    end
  end
end
