# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/EquippedBadgeSettings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.EquippedBadgeSettings" do
    optional :equip_badge_cooldown_ms, :int64, 1
    repeated :catch_probability_bonus, :float, 2
    repeated :flee_probability_bonus, :float, 3
  end
end

module POGOProtos
  module Settings
    module Master
      EquippedBadgeSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.EquippedBadgeSettings").msgclass
    end
  end
end
