# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/GymLevelSettings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.GymLevelSettings" do
    repeated :required_experience, :int32, 1
    repeated :leader_slots, :int32, 2
    repeated :trainer_slots, :int32, 3
    repeated :search_roll_bonus, :int32, 4
  end
end

module POGOProtos
  module Settings
    module Master
      GymLevelSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.GymLevelSettings").msgclass
    end
  end
end
