# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/IapItemDisplay.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/IapItemCategory'
require 'poke-api/POGOProtos/Inventory/Item/ItemId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.IapItemDisplay" do
    optional :sku, :string, 1
    optional :category, :enum, 2, "POGOProtos.Enums.HoloIapItemCategory"
    optional :sort_order, :int32, 3
    repeated :item_ids, :enum, 4, "POGOProtos.Inventory.Item.ItemId"
    repeated :counts, :int32, 5
  end
end

module POGOProtos
  module Settings
    module Master
      IapItemDisplay = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.IapItemDisplay").msgclass
    end
  end
end
