# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/ItemSettings.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/ItemCategory'
require 'poke-api/POGOProtos/Inventory/Item/ItemId'
require 'poke-api/POGOProtos/Inventory/Item/ItemType'
require 'poke-api/POGOProtos/Settings/Master/Item/FoodAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/PotionAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/ReviveAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/BattleAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/IncenseAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/PokeballAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/FortModifierAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/EggIncubatorAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/ExperienceBoostAttributes'
require 'poke-api/POGOProtos/Settings/Master/Item/InventoryUpgradeAttributes'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.ItemSettings" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :item_type, :enum, 2, "POGOProtos.Inventory.Item.ItemType"
    optional :category, :enum, 3, "POGOProtos.Enums.ItemCategory"
    optional :drop_freq, :float, 4
    optional :drop_trainer_level, :int32, 5
    optional :pokeball, :message, 6, "POGOProtos.Settings.Master.Item.PokeballAttributes"
    optional :potion, :message, 7, "POGOProtos.Settings.Master.Item.PotionAttributes"
    optional :revive, :message, 8, "POGOProtos.Settings.Master.Item.ReviveAttributes"
    optional :battle, :message, 9, "POGOProtos.Settings.Master.Item.BattleAttributes"
    optional :food, :message, 10, "POGOProtos.Settings.Master.Item.FoodAttributes"
    optional :inventory_upgrade, :message, 11, "POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes"
    optional :xp_boost, :message, 12, "POGOProtos.Settings.Master.Item.ExperienceBoostAttributes"
    optional :incense, :message, 13, "POGOProtos.Settings.Master.Item.IncenseAttributes"
    optional :egg_incubator, :message, 14, "POGOProtos.Settings.Master.Item.EggIncubatorAttributes"
    optional :fort_modifier, :message, 15, "POGOProtos.Settings.Master.Item.FortModifierAttributes"
  end
end

module POGOProtos
  module Settings
    module Master
      ItemSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.ItemSettings").msgclass
    end
  end
end
