# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/MoveSettings.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonType'
require 'poke-api/POGOProtos/Enums/PokemonMovementType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.MoveSettings" do
    optional :movement_id, :enum, 1, "POGOProtos.Enums.PokemonMovementType"
    optional :animation_id, :int32, 2
    optional :pokemon_type, :enum, 3, "POGOProtos.Enums.PokemonType"
    optional :power, :float, 4
    optional :accuracy_chance, :float, 5
    optional :critical_chance, :float, 6
    optional :heal_scalar, :float, 7
    optional :stamina_loss_scalar, :float, 8
    optional :trainer_level_min, :int32, 9
    optional :trainer_level_max, :int32, 10
    optional :vfx_name, :string, 11
    optional :duration_ms, :int32, 12
    optional :damage_window_start_ms, :int32, 13
    optional :damage_window_end_ms, :int32, 14
    optional :energy_delta, :int32, 15
  end
end

module POGOProtos
  module Settings
    module Master
      MoveSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.MoveSettings").msgclass
    end
  end
end
