# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/MoveSequenceSettings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.MoveSequenceSettings" do
    repeated :sequence, :string, 1
  end
end

module POGOProtos
  module Settings
    module Master
      MoveSequenceSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.MoveSequenceSettings").msgclass
    end
  end
end
