# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/PokemonUpgradeSettings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.PokemonUpgradeSettings" do
    optional :upgrades_per_level, :int32, 1
    optional :allowed_levels_above_player, :int32, 2
    repeated :candy_cost, :int32, 3
    repeated :stardust_cost, :int32, 4
  end
end

module POGOProtos
  module Settings
    module Master
      PokemonUpgradeSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.PokemonUpgradeSettings").msgclass
    end
  end
end
