# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/PokemonSettings.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonId'
require 'poke-api/POGOProtos/Enums/PokemonRarity'
require 'poke-api/POGOProtos/Enums/PokemonType'
require 'poke-api/POGOProtos/Enums/PokemonMove'
require 'poke-api/POGOProtos/Enums/PokemonFamilyId'
require 'poke-api/POGOProtos/Settings/Master/Pokemon/StatsAttributes'
require 'poke-api/POGOProtos/Settings/Master/Pokemon/CameraAttributes'
require 'poke-api/POGOProtos/Settings/Master/Pokemon/EncounterAttributes'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.PokemonSettings" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
    optional :model_scale, :float, 3
    optional :type, :enum, 4, "POGOProtos.Enums.PokemonType"
    optional :type_2, :enum, 5, "POGOProtos.Enums.PokemonType"
    optional :camera, :message, 6, "POGOProtos.Settings.Master.Pokemon.CameraAttributes"
    optional :encounter, :message, 7, "POGOProtos.Settings.Master.Pokemon.EncounterAttributes"
    optional :stats, :message, 8, "POGOProtos.Settings.Master.Pokemon.StatsAttributes"
    repeated :quick_moves, :enum, 9, "POGOProtos.Enums.PokemonMove"
    repeated :cinematic_moves, :enum, 10, "POGOProtos.Enums.PokemonMove"
    repeated :animation_time, :float, 11
    repeated :evolution_ids, :enum, 12, "POGOProtos.Enums.PokemonId"
    optional :evolution_pips, :int32, 13
    optional :rarity, :enum, 14, "POGOProtos.Enums.PokemonRarity"
    optional :pokedex_height_m, :float, 15
    optional :pokedex_weight_kg, :float, 16
    optional :parent_pokemon_id, :enum, 17, "POGOProtos.Enums.PokemonId"
    optional :height_std_dev, :float, 18
    optional :weight_std_dev, :float, 19
    optional :km_distance_to_hatch, :float, 20
    optional :family_id, :enum, 21, "POGOProtos.Enums.PokemonFamilyId"
    optional :candy_to_evolve, :int32, 22
  end
end

module POGOProtos
  module Settings
    module Master
      PokemonSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.PokemonSettings").msgclass
    end
  end
end
