# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/TypeEffectiveSettings.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.TypeEffectiveSettings" do
    repeated :attack_scalar, :float, 1
    optional :attack_type, :enum, 2, "POGOProtos.Enums.PokemonType"
  end
end

module POGOProtos
  module Settings
    module Master
      TypeEffectiveSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.TypeEffectiveSettings").msgclass
    end
  end
end
