# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/CheckCodenameAvailableMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.CheckCodenameAvailableMessage" do
    optional :codename, :string, 1
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        CheckCodenameAvailableMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.CheckCodenameAvailableMessage").msgclass
      end
    end
  end
end
