# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DownloadSettingsMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.DownloadSettingsMessage" do
    optional :hash, :string, 1
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        DownloadSettingsMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.DownloadSettingsMessage").msgclass
      end
    end
  end
end
