# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/EncounterTutorialCompleteMessage.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        EncounterTutorialCompleteMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.EncounterTutorialCompleteMessage").msgclass
      end
    end
  end
end
