# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/EquipBadgeMessage.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/BadgeType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.EquipBadgeMessage" do
    optional :badge_type, :enum, 1, "POGOProtos.Enums.BadgeType"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        EquipBadgeMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.EquipBadgeMessage").msgclass
      end
    end
  end
end
