# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetDownloadUrlsMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetDownloadUrlsMessage" do
    repeated :asset_id, :string, 1
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetDownloadUrlsMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetDownloadUrlsMessage").msgclass
      end
    end
  end
end
