# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetGymDetailsMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetGymDetailsMessage" do
    optional :gym_id, :string, 1
    optional :player_latitude, :double, 2
    optional :player_longitude, :double, 3
    optional :gym_latitude, :double, 4
    optional :gym_longitude, :double, 5
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetGymDetailsMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetGymDetailsMessage").msgclass
      end
    end
  end
end
