# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetInventoryMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetInventoryMessage" do
    optional :last_timestamp_ms, :int64, 1
    optional :item_been_seen, :int32, 2
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetInventoryMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetInventoryMessage").msgclass
      end
    end
  end
end
