# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetMapObjectsMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetMapObjectsMessage" do
    repeated :cell_id, :uint64, 1
    repeated :since_timestamp_ms, :int64, 2
    optional :latitude, :double, 3
    optional :longitude, :double, 4
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetMapObjectsMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetMapObjectsMessage").msgclass
      end
    end
  end
end
