# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetSuggestedCodenamesMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.GetSuggestedCodenamesMessage" do
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        GetSuggestedCodenamesMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.GetSuggestedCodenamesMessage").msgclass
      end
    end
  end
end
