# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/LevelUpRewardsMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessage" do
    optional :level, :int32, 1
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        LevelUpRewardsMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.LevelUpRewardsMessage").msgclass
      end
    end
  end
end
