# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/NicknamePokemonMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.NicknamePokemonMessage" do
    optional :pokemon_id, :fixed64, 1
    optional :nickname, :string, 2
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        NicknamePokemonMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.NicknamePokemonMessage").msgclass
      end
    end
  end
end
