# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetAvatarMessage.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Player/PlayerAvatar'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SetAvatarMessage" do
    optional :player_avatar, :message, 2, "POGOProtos.Data.Player.PlayerAvatar"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SetAvatarMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SetAvatarMessage").msgclass
      end
    end
  end
end
