# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetContactSettingsMessage.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Player/ContactSettings'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SetContactSettingsMessage" do
    optional :contact_settings, :message, 1, "POGOProtos.Data.Player.ContactSettings"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SetContactSettingsMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SetContactSettingsMessage").msgclass
      end
    end
  end
end
