# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetPlayerTeamMessage.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/TeamColor'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage" do
    optional :team, :enum, 1, "POGOProtos.Enums.TeamColor"
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SetPlayerTeamMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SetPlayerTeamMessage").msgclass
      end
    end
  end
end
