# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SfidaActionLogMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.SfidaActionLogMessage" do
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        SfidaActionLogMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.SfidaActionLogMessage").msgclass
      end
    end
  end
end
