# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/StartGymBattleMessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.StartGymBattleMessage" do
    optional :gym_id, :string, 1
    repeated :attacking_pokemon_ids, :fixed64, 2
    optional :defending_pokemon_id, :uint64, 3
    optional :player_latitude, :double, 4
    optional :player_longitude, :double, 5
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        StartGymBattleMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.StartGymBattleMessage").msgclass
      end
    end
  end
end
