# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UseItemCaptureMessage.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/Item/ItemId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Requests.Messages.UseItemCaptureMessage" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :encounter_id, :fixed64, 2
    optional :spawn_point_id, :string, 3
  end
end

module POGOProtos
  module Networking
    module Requests
      module Messages
        UseItemCaptureMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Requests.Messages.UseItemCaptureMessage").msgclass
      end
    end
  end
end
