# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortSponsor.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Map.Fort.FortSponsor" do
    value :UNSET_SPONSOR, 0
    value :MCDONALDS, 1
    value :POKEMON_STORE, 2
  end
end

module POGOProtos
  module Map
    module Fort
      FortSponsor = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortSponsor").enummodule
    end
  end
end
