# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortRenderingType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Map.Fort.FortRenderingType" do
    value :DEFAULT, 0
    value :INTERNAL_TEST, 1
  end
end

module POGOProtos
  module Map
    module Fort
      FortRenderingType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortRenderingType").enummodule
    end
  end
end
