# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortSummary.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.Fort.FortSummary" do
    optional :fort_summary_id, :string, 1
    optional :last_modified_timestamp_ms, :int64, 2
    optional :latitude, :double, 3
    optional :longitude, :double, 4
  end
end

module POGOProtos
  module Map
    module Fort
      FortSummary = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortSummary").msgclass
    end
  end
end
