# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortData.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonId'
require 'poke-api/POGOProtos/Enums/TeamColor'
require 'poke-api/POGOProtos/Map/Fort/FortType'
require 'poke-api/POGOProtos/Map/Fort/FortSponsor'
require 'poke-api/POGOProtos/Map/Fort/FortRenderingType'
require 'poke-api/POGOProtos/Map/Fort/FortLureInfo'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Map.Fort.FortData" do
    optional :id, :string, 1
    optional :last_modified_timestamp_ms, :int64, 2
    optional :latitude, :double, 3
    optional :longitude, :double, 4
    optional :enabled, :bool, 8
    optional :type, :enum, 9, "POGOProtos.Map.Fort.FortType"
    optional :owned_by_team, :enum, 5, "POGOProtos.Enums.TeamColor"
    optional :guard_pokemon_id, :enum, 6, "POGOProtos.Enums.PokemonId"
    optional :guard_pokemon_cp, :int32, 7
    optional :gym_points, :int64, 10
    optional :is_in_battle, :bool, 11
    optional :cooldown_complete_timestamp_ms, :int64, 14
    optional :sponsor, :enum, 15, "POGOProtos.Map.Fort.FortSponsor"
    optional :rendering_type, :enum, 16, "POGOProtos.Map.Fort.FortRenderingType"
    optional :active_fort_modifier, :bytes, 12
    optional :lure_info, :message, 13, "POGOProtos.Map.Fort.FortLureInfo"
  end
end

module POGOProtos
  module Map
    module Fort
      FortData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortData").msgclass
    end
  end
end
