# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Map.Fort.FortType" do
    value :GYM, 0
    value :CHECKPOINT, 1
  end
end

module POGOProtos
  module Map
    module Fort
      FortType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Map.Fort.FortType").enummodule
    end
  end
end
