# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/EggIncubatorAttributes.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/EggIncubatorType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.EggIncubatorAttributes" do
    optional :incubator_type, :enum, 1, "POGOProtos.Inventory.EggIncubatorType"
    optional :uses, :int32, 2
    optional :distance_multiplier, :float, 3
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        EggIncubatorAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.EggIncubatorAttributes").msgclass
      end
    end
  end
end
