# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/ExperienceBoostAttributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.ExperienceBoostAttributes" do
    optional :xp_multiplier, :float, 1
    optional :boost_duration_ms, :int32, 2
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        ExperienceBoostAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.ExperienceBoostAttributes").msgclass
      end
    end
  end
end
