# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/FoodAttributes.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/ItemEffect'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.FoodAttributes" do
    repeated :item_effect, :enum, 1, "POGOProtos.Enums.ItemEffect"
    repeated :item_effect_percent, :float, 2
    optional :growth_percent, :float, 3
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        FoodAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.FoodAttributes").msgclass
      end
    end
  end
end
