# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/FortModifierAttributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.FortModifierAttributes" do
    optional :modifier_lifetime_seconds, :int32, 1
    optional :troy_disk_num_pokemon_spawned, :int32, 2
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        FortModifierAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.FortModifierAttributes").msgclass
      end
    end
  end
end
