# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/InventoryUpgradeAttributes.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/InventoryUpgradeType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes" do
    optional :additional_storage, :int32, 1
    optional :upgrade_type, :enum, 2, "POGOProtos.Inventory.InventoryUpgradeType"
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        InventoryUpgradeAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.InventoryUpgradeAttributes").msgclass
      end
    end
  end
end
