# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/ReviveAttributes.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Item.ReviveAttributes" do
    optional :sta_percent, :float, 1
  end
end

module POGOProtos
  module Settings
    module Master
      module Item
        ReviveAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Item.ReviveAttributes").msgclass
      end
    end
  end
end
