# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/AppliedItems.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/AppliedItem'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.AppliedItems" do
    repeated :item, :message, 4, "POGOProtos.Inventory.AppliedItem"
  end
end

module POGOProtos
  module Inventory
    AppliedItems = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.AppliedItems").msgclass
  end
end
