# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryUpgrades.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/InventoryUpgrade'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryUpgrades" do
    repeated :inventory_upgrades, :message, 1, "POGOProtos.Inventory.InventoryUpgrade"
  end
end

module POGOProtos
  module Inventory
    InventoryUpgrades = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryUpgrades").msgclass
  end
end
