# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryItem.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/InventoryItemData'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryItem" do
    optional :modified_timestamp_ms, :int64, 1
    optional :deleted_item_key, :int64, 2
    optional :inventory_item_data, :message, 3, "POGOProtos.Inventory.InventoryItemData"
  end
end

module POGOProtos
  module Inventory
    InventoryItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryItem").msgclass
  end
end
