# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryUpgradeType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "POGOProtos.Inventory.InventoryUpgradeType" do
    value :UPGRADE_UNSET, 0
    value :INCREASE_ITEM_STORAGE, 1
    value :INCREASE_POKEMON_STORAGE, 2
  end
end

module POGOProtos
  module Inventory
    InventoryUpgradeType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryUpgradeType").enummodule
  end
end
