# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryUpgrade.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Inventory/Item/ItemId'
require 'poke-api/POGOProtos/Inventory/InventoryUpgradeType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.InventoryUpgrade" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :upgrade_type, :enum, 2, "POGOProtos.Inventory.InventoryUpgradeType"
    optional :additional_storage, :int32, 3
  end
end

module POGOProtos
  module Inventory
    InventoryUpgrade = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.InventoryUpgrade").msgclass
  end
end
