# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/PokemonFamily.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/PokemonFamilyId'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.PokemonFamily" do
    optional :family_id, :enum, 1, "POGOProtos.Enums.PokemonFamilyId"
    optional :candy, :int32, 2
  end
end

module POGOProtos
  module Inventory
    PokemonFamily = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.PokemonFamily").msgclass
  end
end
