# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Envelopes/AuthTicket.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Envelopes.AuthTicket" do
    optional :start, :bytes, 1
    optional :expire_timestamp_ms, :uint64, 2
    optional :end, :bytes, 3
  end
end

module POGOProtos
  module Networking
    module Envelopes
      AuthTicket = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.AuthTicket").msgclass
    end
  end
end
