# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Envelopes/ResponseEnvelope.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Networking/Envelopes/AuthTicket'
require 'poke-api/POGOProtos/Networking/Envelopes/Unknown6Response'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Envelopes.ResponseEnvelope" do
    optional :status_code, :int32, 1
    optional :request_id, :uint64, 2
    optional :api_url, :string, 3
    optional :unknown6, :message, 6, "POGOProtos.Networking.Envelopes.Unknown6Response"
    optional :auth_ticket, :message, 7, "POGOProtos.Networking.Envelopes.AuthTicket"
    repeated :returns, :bytes, 100
    optional :error, :string, 101
  end
  add_message "POGOProtos.Networking.Envelopes.ResponseEnvelope.Unknown7" do
    optional :unknown71, :bytes, 1
    optional :unknown72, :int64, 2
    optional :unknown73, :bytes, 3
  end
end

module POGOProtos
  module Networking
    module Envelopes
      ResponseEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.ResponseEnvelope").msgclass
      ResponseEnvelope::Unknown7 = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.ResponseEnvelope.Unknown7").msgclass
    end
  end
end
