# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Envelopes/Unknown6.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Envelopes.Unknown6" do
    optional :unknown1, :int32, 1
    optional :unknown2, :message, 2, "POGOProtos.Networking.Envelopes.Unknown6.Unknown2"
  end
  add_message "POGOProtos.Networking.Envelopes.Unknown6.Unknown2" do
    optional :unknown1, :bytes, 1
  end
end

module POGOProtos
  module Networking
    module Envelopes
      Unknown6 = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6").msgclass
      Unknown6::Unknown2 = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6.Unknown2").msgclass
    end
  end
end
