# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/ContactSettings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Player.ContactSettings" do
    optional :send_marketing_emails, :bool, 1
    optional :send_push_notifications, :bool, 2
  end
end

module POGOProtos
  module Data
    module Player
      ContactSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.ContactSettings").msgclass
    end
  end
end
