# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/EquippedBadge.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/BadgeType'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Player.EquippedBadge" do
    optional :badge_type, :enum, 1, "POGOProtos.Enums.BadgeType"
    optional :level, :int32, 2
    optional :next_equip_change_allowed_timestamp_ms, :int64, 3
  end
end

module POGOProtos
  module Data
    module Player
      EquippedBadge = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.EquippedBadge").msgclass
    end
  end
end
