# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerCurrency.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Player.PlayerCurrency" do
    optional :gems, :int32, 1
  end
end

module POGOProtos
  module Data
    module Player
      PlayerCurrency = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.PlayerCurrency").msgclass
    end
  end
end
