# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerAvatar.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Enums/Gender'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Player.PlayerAvatar" do
    optional :skin, :int32, 2
    optional :hair, :int32, 3
    optional :shirt, :int32, 4
    optional :pants, :int32, 5
    optional :hat, :int32, 6
    optional :shoes, :int32, 7
    optional :gender, :enum, 8, "POGOProtos.Enums.Gender"
    optional :eyes, :int32, 9
    optional :backpack, :int32, 10
  end
end

module POGOProtos
  module Data
    module Player
      PlayerAvatar = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.PlayerAvatar").msgclass
    end
  end
end
