# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerPublicProfile.proto

require 'google/protobuf'

require 'poke-api/POGOProtos/Data/Player/PlayerAvatar'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Player.PlayerPublicProfile" do
    optional :name, :string, 1
    optional :level, :int32, 2
    optional :avatar, :message, 3, "POGOProtos.Data.Player.PlayerAvatar"
  end
end

module POGOProtos
  module Data
    module Player
      PlayerPublicProfile = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Player.PlayerPublicProfile").msgclass
    end
  end
end
