# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Inventory.Item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Inventory.Item.ItemAward" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :item_count, :int32, 2
  end
  add_message "POGOProtos.Inventory.Item.ItemData" do
    optional :item_id, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    optional :count, :int32, 2
    optional :unseen, :bool, 3
  end
  add_enum "POGOProtos.Inventory.Item.ItemType" do
    value :ITEM_TYPE_NONE, 0
    value :ITEM_TYPE_POKEBALL, 1
    value :ITEM_TYPE_POTION, 2
    value :ITEM_TYPE_REVIVE, 3
    value :ITEM_TYPE_MAP, 4
    value :ITEM_TYPE_BATTLE, 5
    value :ITEM_TYPE_FOOD, 6
    value :ITEM_TYPE_CAMERA, 7
    value :ITEM_TYPE_DISK, 8
    value :ITEM_TYPE_INCUBATOR, 9
    value :ITEM_TYPE_INCENSE, 10
    value :ITEM_TYPE_XP_BOOST, 11
    value :ITEM_TYPE_INVENTORY_UPGRADE, 12
  end
  add_enum "POGOProtos.Inventory.Item.ItemId" do
    value :ITEM_UNKNOWN, 0
    value :ITEM_POKE_BALL, 1
    value :ITEM_GREAT_BALL, 2
    value :ITEM_ULTRA_BALL, 3
    value :ITEM_MASTER_BALL, 4
    value :ITEM_POTION, 101
    value :ITEM_SUPER_POTION, 102
    value :ITEM_HYPER_POTION, 103
    value :ITEM_MAX_POTION, 104
    value :ITEM_REVIVE, 201
    value :ITEM_MAX_REVIVE, 202
    value :ITEM_LUCKY_EGG, 301
    value :ITEM_INCENSE_ORDINARY, 401
    value :ITEM_INCENSE_SPICY, 402
    value :ITEM_INCENSE_COOL, 403
    value :ITEM_INCENSE_FLORAL, 404
    value :ITEM_TROY_DISK, 501
    value :ITEM_X_ATTACK, 602
    value :ITEM_X_DEFENSE, 603
    value :ITEM_X_MIRACLE, 604
    value :ITEM_RAZZ_BERRY, 701
    value :ITEM_BLUK_BERRY, 702
    value :ITEM_NANAB_BERRY, 703
    value :ITEM_WEPAR_BERRY, 704
    value :ITEM_PINAP_BERRY, 705
    value :ITEM_SPECIAL_CAMERA, 801
    value :ITEM_INCUBATOR_BASIC_UNLIMITED, 901
    value :ITEM_INCUBATOR_BASIC, 902
    value :ITEM_POKEMON_STORAGE_UPGRADE, 1001
    value :ITEM_ITEM_STORAGE_UPGRADE, 1002
  end
end

module POGOProtos
  module Inventory
    module Item
      ItemAward = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.Item.ItemAward").msgclass
      ItemData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.Item.ItemData").msgclass
      ItemType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.Item.ItemType").enummodule
      ItemId = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Inventory.Item.ItemId").enummodule
    end
  end
end
