# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Data.Capture.proto

require 'google/protobuf'

require_relative 'pogoprotos_enums'
require_relative 'pogoprotos_inventory_item'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Capture.CaptureAward" do
    repeated :activity_type, :enum, 1, "POGOProtos.Enums.ActivityType"
    repeated :xp, :int32, 2
    repeated :candy, :int32, 3
    repeated :stardust, :int32, 4
  end
  add_message "POGOProtos.Data.Capture.CaptureProbability" do
    repeated :pokeball_type, :enum, 1, "POGOProtos.Inventory.Item.ItemId"
    repeated :capture_probability, :float, 2
    optional :reticle_difficulty_scale, :double, 12
  end
end

module POGOProtos
  module Data
    module Capture
      CaptureAward = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Capture.CaptureAward").msgclass
      CaptureProbability = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Capture.CaptureProbability").msgclass
    end
  end
end
