# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Networking.Envelopes.proto

require 'google/protobuf'

require_relative 'pogoprotos_data_player'
require_relative 'pogoprotos_inventory_item'
require_relative 'pogoprotos_networking_requests'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Networking.Envelopes.Signature" do
    optional :timestamp_since_start, :uint64, 2
    repeated :location_fix, :message, 4, "POGOProtos.Networking.Envelopes.Signature.LocationFix"
    optional :android_gps_info, :message, 5, "POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo"
    optional :sensor_info, :message, 7, "POGOProtos.Networking.Envelopes.Signature.SensorInfo"
    optional :device_info, :message, 8, "POGOProtos.Networking.Envelopes.Signature.DeviceInfo"
    optional :activity_status, :message, 9, "POGOProtos.Networking.Envelopes.Signature.ActivityStatus"
    optional :location_hash1, :uint64, 10
    optional :location_hash2, :uint64, 20
    optional :session_hash, :bytes, 22
    optional :timestamp, :uint64, 23
    repeated :request_hash, :uint64, 24
    optional :unknown25, :int64, 25
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.LocationFix" do
    optional :provider, :string, 1
    optional :timestamp_snapshot, :uint64, 2
    optional :latitude, :float, 13
    optional :longitude, :float, 14
    optional :horizontal_accuracy, :float, 20
    optional :altitude, :float, 21
    optional :vertical_accuracy, :float, 22
    optional :provider_status, :uint64, 26
    optional :floor, :uint32, 27
    optional :location_type, :uint64, 28
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo" do
    optional :time_to_fix, :uint64, 1
    repeated :satellites_prn, :int32, 2
    repeated :snr, :float, 3
    repeated :azimuth, :float, 4
    repeated :elevation, :float, 5
    repeated :has_almanac, :bool, 6
    repeated :has_ephemeris, :bool, 7
    repeated :used_in_fix, :bool, 8
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.SensorInfo" do
    optional :timestamp_snapshot, :uint64, 1
    optional :magnetometer_x, :double, 3
    optional :magnetometer_y, :double, 4
    optional :magnetometer_z, :double, 5
    optional :angle_normalized_x, :double, 6
    optional :angle_normalized_y, :double, 7
    optional :angle_normalized_z, :double, 8
    optional :accel_raw_x, :double, 10
    optional :accel_raw_y, :double, 11
    optional :accel_raw_z, :double, 12
    optional :gyroscope_raw_x, :double, 13
    optional :gyroscope_raw_y, :double, 14
    optional :gyroscope_raw_z, :double, 15
    optional :accel_normalized_x, :double, 16
    optional :accel_normalized_y, :double, 17
    optional :accel_normalized_z, :double, 18
    optional :accelerometer_axes, :uint64, 19
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.DeviceInfo" do
    optional :device_id, :string, 1
    optional :android_board_name, :string, 2
    optional :android_bootloader, :string, 3
    optional :device_brand, :string, 4
    optional :device_model, :string, 5
    optional :device_model_identifier, :string, 6
    optional :device_model_boot, :string, 7
    optional :hardware_manufacturer, :string, 8
    optional :hardware_model, :string, 9
    optional :firmware_brand, :string, 10
    optional :firmware_tags, :string, 12
    optional :firmware_type, :string, 13
    optional :firmware_fingerprint, :string, 14
  end
  add_message "POGOProtos.Networking.Envelopes.Signature.ActivityStatus" do
    optional :start_time_ms, :uint64, 1
    optional :unknown_status, :bool, 2
    optional :walking, :bool, 3
    optional :running, :bool, 4
    optional :stationary, :bool, 5
    optional :automotive, :bool, 6
    optional :tilting, :bool, 7
    optional :cycling, :bool, 8
    optional :status, :bytes, 9
  end
  add_message "POGOProtos.Networking.Envelopes.Unknown6" do
    optional :request_type, :int32, 1
    optional :unknown2, :message, 2, "POGOProtos.Networking.Envelopes.Unknown6.Unknown2"
  end
  add_message "POGOProtos.Networking.Envelopes.Unknown6.Unknown2" do
    optional :encrypted_signature, :bytes, 1
  end
  add_message "POGOProtos.Networking.Envelopes.AuthTicket" do
    optional :start, :bytes, 1
    optional :expire_timestamp_ms, :uint64, 2
    optional :end, :bytes, 3
  end
  add_message "POGOProtos.Networking.Envelopes.ResponseEnvelope" do
    optional :status_code, :int32, 1
    optional :request_id, :uint64, 2
    optional :api_url, :string, 3
    repeated :unknown6, :message, 6, "POGOProtos.Networking.Envelopes.Unknown6Response"
    optional :auth_ticket, :message, 7, "POGOProtos.Networking.Envelopes.AuthTicket"
    repeated :returns, :bytes, 100
    optional :error, :string, 101
  end
  add_message "POGOProtos.Networking.Envelopes.Unknown6Response" do
    optional :response_type, :int32, 1
    optional :unknown2, :message, 2, "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2"
  end
  add_message "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2" do
    optional :unknown1, :uint64, 1
    repeated :items, :message, 2, "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem"
    repeated :player_currencies, :message, 3, "POGOProtos.Data.Player.Currency"
    optional :unknown4, :string, 4
  end
  add_message "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem" do
    optional :item_id, :string, 1
    optional :is_iap, :bool, 2
    optional :currency_to_buy, :message, 3, "POGOProtos.Data.Player.Currency"
    optional :yields_currency, :message, 4, "POGOProtos.Data.Player.Currency"
    optional :yields_item, :message, 5, "POGOProtos.Inventory.Item.ItemData"
    repeated :tags, :message, 6, "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem.Tag"
    optional :unknown7, :int32, 7
  end
  add_message "POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem.Tag" do
    optional :key, :string, 1
    optional :value, :string, 2
  end
  add_message "POGOProtos.Networking.Envelopes.RequestEnvelope" do
    optional :status_code, :int32, 1
    optional :request_id, :uint64, 3
    repeated :requests, :message, 4, "POGOProtos.Networking.Requests.Request"
    optional :unknown6, :message, 6, "POGOProtos.Networking.Envelopes.Unknown6"
    optional :latitude, :double, 7
    optional :longitude, :double, 8
    optional :altitude, :double, 9
    optional :auth_info, :message, 10, "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo"
    optional :auth_ticket, :message, 11, "POGOProtos.Networking.Envelopes.AuthTicket"
    optional :unknown12, :int64, 12
  end
  add_message "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo" do
    optional :provider, :string, 1
    optional :token, :message, 2, "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT"
  end
  add_message "POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT" do
    optional :contents, :string, 1
    optional :unknown2, :int32, 2
  end
end

module POGOProtos
  module Networking
    module Envelopes
      Signature = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature").msgclass
      Signature::LocationFix = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.LocationFix").msgclass
      Signature::AndroidGpsInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.AndroidGpsInfo").msgclass
      Signature::SensorInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.SensorInfo").msgclass
      Signature::DeviceInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.DeviceInfo").msgclass
      Signature::ActivityStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Signature.ActivityStatus").msgclass
      Unknown6 = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6").msgclass
      Unknown6::Unknown2 = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6.Unknown2").msgclass
      AuthTicket = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.AuthTicket").msgclass
      ResponseEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.ResponseEnvelope").msgclass
      Unknown6Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6Response").msgclass
      Unknown6Response::Unknown2 = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2").msgclass
      Unknown6Response::Unknown2::StoreItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem").msgclass
      Unknown6Response::Unknown2::StoreItem::Tag = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.Unknown6Response.Unknown2.StoreItem.Tag").msgclass
      RequestEnvelope = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.RequestEnvelope").msgclass
      RequestEnvelope::AuthInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo").msgclass
      RequestEnvelope::AuthInfo::JWT = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Networking.Envelopes.RequestEnvelope.AuthInfo.JWT").msgclass
    end
  end
end
