# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Data.Battle.proto

require 'google/protobuf'

require_relative 'pogoprotos_data'
require_relative 'pogoprotos_data_player'
require_relative 'pogoprotos_data_gym'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Battle.BattlePokemonInfo" do
    optional :pokemon_data, :message, 1, "POGOProtos.Data.PokemonData"
    optional :current_health, :int32, 2
    optional :current_energy, :int32, 3
  end
  add_message "POGOProtos.Data.Battle.BattleParticipant" do
    optional :active_pokemon, :message, 1, "POGOProtos.Data.Battle.BattlePokemonInfo"
    optional :trainer_public_profile, :message, 2, "POGOProtos.Data.Player.PlayerPublicProfile"
    repeated :reverse_pokemon, :message, 3, "POGOProtos.Data.Battle.BattlePokemonInfo"
    repeated :defeated_pokemon, :message, 4, "POGOProtos.Data.Battle.BattlePokemonInfo"
  end
  add_message "POGOProtos.Data.Battle.BattleResults" do
    optional :gym_state, :message, 1, "POGOProtos.Data.Gym.GymState"
    repeated :attackers, :message, 2, "POGOProtos.Data.Battle.BattleParticipant"
    repeated :player_experience_awarded, :int32, 3
    optional :next_defender_pokemon_id, :int64, 4
    optional :gym_points_delta, :int32, 5
  end
  add_message "POGOProtos.Data.Battle.BattleAction" do
    optional :Type, :enum, 1, "POGOProtos.Data.Battle.BattleActionType"
    optional :action_start_ms, :int64, 2
    optional :duration_ms, :int32, 3
    optional :energy_delta, :int32, 5
    optional :attacker_index, :int32, 6
    optional :target_index, :int32, 7
    optional :active_pokemon_id, :fixed64, 8
    optional :player_joined, :message, 9, "POGOProtos.Data.Battle.BattleParticipant"
    optional :battle_results, :message, 10, "POGOProtos.Data.Battle.BattleResults"
    optional :damage_windows_start_timestamp_mss, :int64, 11
    optional :damage_windows_end_timestamp_mss, :int64, 12
    optional :player_left, :message, 13, "POGOProtos.Data.Battle.BattleParticipant"
    optional :target_pokemon_id, :fixed64, 14
  end
  add_message "POGOProtos.Data.Battle.BattleLog" do
    optional :state, :enum, 1, "POGOProtos.Data.Battle.BattleState"
    optional :battle_type, :enum, 2, "POGOProtos.Data.Battle.BattleType"
    optional :server_ms, :int64, 3
    repeated :battle_actions, :message, 4, "POGOProtos.Data.Battle.BattleAction"
    optional :battle_start_timestamp_ms, :int64, 5
    optional :battle_end_timestamp_ms, :int64, 6
  end
  add_enum "POGOProtos.Data.Battle.BattleType" do
    value :BATTLE_TYPE_UNSET, 0
    value :BATTLE_TYPE_NORMAL, 1
    value :BATTLE_TYPE_TRAINING, 2
  end
  add_enum "POGOProtos.Data.Battle.BattleState" do
    value :STATE_UNSET, 0
    value :ACTIVE, 1
    value :VICTORY, 2
    value :DEFEATED, 3
    value :TIMED_OUT, 4
  end
  add_enum "POGOProtos.Data.Battle.BattleActionType" do
    value :ACTION_UNSET, 0
    value :ACTION_ATTACK, 1
    value :ACTION_DODGE, 2
    value :ACTION_SPECIAL_ATTACK, 3
    value :ACTION_SWAP_POKEMON, 4
    value :ACTION_FAINT, 5
    value :ACTION_PLAYER_JOIN, 6
    value :ACTION_PLAYER_QUIT, 7
    value :ACTION_VICTORY, 8
    value :ACTION_DEFEAT, 9
    value :ACTION_TIMED_OUT, 10
  end
end

module POGOProtos
  module Data
    module Battle
      BattlePokemonInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattlePokemonInfo").msgclass
      BattleParticipant = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleParticipant").msgclass
      BattleResults = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleResults").msgclass
      BattleAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleAction").msgclass
      BattleLog = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleLog").msgclass
      BattleType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleType").enummodule
      BattleState = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleState").enummodule
      BattleActionType = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Battle.BattleActionType").enummodule
    end
  end
end
