# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Settings.Master.Pokemon.proto

require 'google/protobuf'

require_relative 'pogoprotos_enums'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.Master.Pokemon.CameraAttributes" do
    optional :disk_radius_m, :float, 1
    optional :cylinder_radius_m, :float, 2
    optional :cylinder_height_m, :float, 3
    optional :cylinder_ground_m, :float, 4
    optional :shoulder_mode_scale, :float, 5
  end
  add_message "POGOProtos.Settings.Master.Pokemon.EncounterAttributes" do
    optional :base_capture_rate, :float, 1
    optional :base_flee_rate, :float, 2
    optional :collision_radius_m, :float, 3
    optional :collision_height_m, :float, 4
    optional :collision_head_radius_m, :float, 5
    optional :movement_type, :enum, 6, "POGOProtos.Enums.PokemonMovementType"
    optional :movement_timer_s, :float, 7
    optional :jump_time_s, :float, 8
    optional :attack_timer_s, :float, 9
  end
  add_message "POGOProtos.Settings.Master.Pokemon.StatsAttributes" do
    optional :base_stamina, :int32, 1
    optional :base_attack, :int32, 2
    optional :base_defense, :int32, 3
    optional :dodge_energy_delta, :int32, 8
  end
end

module POGOProtos
  module Settings
    module Master
      module Pokemon
        CameraAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Pokemon.CameraAttributes").msgclass
        EncounterAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Pokemon.EncounterAttributes").msgclass
        StatsAttributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.Master.Pokemon.StatsAttributes").msgclass
      end
    end
  end
end
