# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Data.Gym.proto

require 'google/protobuf'

require_relative 'pogoprotos_data'
require_relative 'pogoprotos_data_player'
require_relative 'pogoprotos_map_fort'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.Gym.GymMembership" do
    optional :pokemon_data, :message, 1, "POGOProtos.Data.PokemonData"
    optional :trainer_public_profile, :message, 2, "POGOProtos.Data.Player.PlayerPublicProfile"
  end
  add_message "POGOProtos.Data.Gym.GymState" do
    optional :fort_data, :message, 1, "POGOProtos.Map.Fort.FortData"
    repeated :memberships, :message, 2, "POGOProtos.Data.Gym.GymMembership"
  end
end

module POGOProtos
  module Data
    module Gym
      GymMembership = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Gym.GymMembership").msgclass
      GymState = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.Gym.GymState").msgclass
    end
  end
end
