# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Data.proto

require 'google/protobuf'

require_relative 'pogoprotos_enums'
require_relative 'pogoprotos_inventory_item'
require_relative 'pogoprotos_data_player'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Data.PokemonData" do
    optional :id, :fixed64, 1
    optional :pokemon_id, :enum, 2, "POGOProtos.Enums.PokemonId"
    optional :cp, :int32, 3
    optional :stamina, :int32, 4
    optional :stamina_max, :int32, 5
    optional :move_1, :enum, 6, "POGOProtos.Enums.PokemonMove"
    optional :move_2, :enum, 7, "POGOProtos.Enums.PokemonMove"
    optional :deployed_fort_id, :string, 8
    optional :owner_name, :string, 9
    optional :is_egg, :bool, 10
    optional :egg_km_walked_target, :double, 11
    optional :egg_km_walked_start, :double, 12
    optional :origin, :int32, 14
    optional :height_m, :float, 15
    optional :weight_kg, :float, 16
    optional :individual_attack, :int32, 17
    optional :individual_defense, :int32, 18
    optional :individual_stamina, :int32, 19
    optional :cp_multiplier, :float, 20
    optional :pokeball, :enum, 21, "POGOProtos.Inventory.Item.ItemId"
    optional :captured_cell_id, :uint64, 22
    optional :battles_attacked, :int32, 23
    optional :battles_defended, :int32, 24
    optional :egg_incubator_id, :string, 25
    optional :creation_time_ms, :uint64, 26
    optional :num_upgrades, :int32, 27
    optional :additional_cp_multiplier, :float, 28
    optional :favorite, :int32, 29
    optional :nickname, :string, 30
    optional :from_fort, :int32, 31
  end
  add_message "POGOProtos.Data.PlayerData" do
    optional :creation_timestamp_ms, :int64, 1
    optional :username, :string, 2
    optional :team, :enum, 5, "POGOProtos.Enums.TeamColor"
    repeated :tutorial_state, :enum, 7, "POGOProtos.Enums.TutorialState"
    optional :avatar, :message, 8, "POGOProtos.Data.Player.PlayerAvatar"
    optional :max_pokemon_storage, :int32, 9
    optional :max_item_storage, :int32, 10
    optional :daily_bonus, :message, 11, "POGOProtos.Data.Player.DailyBonus"
    optional :equipped_badge, :message, 12, "POGOProtos.Data.Player.EquippedBadge"
    optional :contact_settings, :message, 13, "POGOProtos.Data.Player.ContactSettings"
    repeated :currencies, :message, 14, "POGOProtos.Data.Player.Currency"
    optional :remaining_codename_claims, :int32, 15
  end
  add_message "POGOProtos.Data.AssetDigestEntry" do
    optional :asset_id, :string, 1
    optional :bundle_name, :string, 2
    optional :version, :int64, 3
    optional :checksum, :fixed32, 4
    optional :size, :int32, 5
    optional :key, :bytes, 6
  end
  add_message "POGOProtos.Data.PokedexEntry" do
    optional :pokemon_id, :enum, 1, "POGOProtos.Enums.PokemonId"
    optional :times_encountered, :int32, 2
    optional :times_captured, :int32, 3
    optional :evolution_stone_pieces, :int32, 4
    optional :evolution_stones, :int32, 5
  end
  add_message "POGOProtos.Data.DownloadUrlEntry" do
    optional :asset_id, :string, 1
    optional :url, :string, 2
    optional :size, :int32, 3
    optional :checksum, :fixed32, 4
  end
  add_message "POGOProtos.Data.PlayerBadge" do
    optional :badge_type, :enum, 1, "POGOProtos.Enums.BadgeType"
    optional :rank, :int32, 2
    optional :start_value, :int32, 3
    optional :end_value, :int32, 4
    optional :current_value, :double, 5
  end
end

module POGOProtos
  module Data
    PokemonData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PokemonData").msgclass
    PlayerData = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PlayerData").msgclass
    AssetDigestEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.AssetDigestEntry").msgclass
    PokedexEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PokedexEntry").msgclass
    DownloadUrlEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.DownloadUrlEntry").msgclass
    PlayerBadge = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Data.PlayerBadge").msgclass
  end
end
