# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos.Settings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "POGOProtos.Settings.MapSettings" do
    optional :pokemon_visible_range, :double, 1
    optional :poke_nav_range_meters, :double, 2
    optional :encounter_range_meters, :double, 3
    optional :get_map_objects_min_refresh_seconds, :float, 4
    optional :get_map_objects_max_refresh_seconds, :float, 5
    optional :get_map_objects_min_distance_meters, :float, 6
    optional :google_maps_api_key, :string, 7
  end
  add_message "POGOProtos.Settings.FortSettings" do
    optional :interaction_range_meters, :double, 1
    optional :max_total_deployed_pokemon, :int32, 2
    optional :max_player_deployed_pokemon, :int32, 3
    optional :deploy_stamina_multiplier, :double, 4
    optional :deploy_attack_multiplier, :double, 5
    optional :far_interaction_range_meters, :double, 6
  end
  add_message "POGOProtos.Settings.GpsSettings" do
    optional :driving_warning_speed_meters_per_second, :float, 1
    optional :driving_warning_cooldown_minutes, :float, 2
    optional :driving_speed_sample_interval_seconds, :float, 3
    optional :driving_speed_sample_count, :int32, 4
  end
  add_message "POGOProtos.Settings.GlobalSettings" do
    optional :fort_settings, :message, 2, "POGOProtos.Settings.FortSettings"
    optional :map_settings, :message, 3, "POGOProtos.Settings.MapSettings"
    optional :level_settings, :message, 4, "POGOProtos.Settings.LevelSettings"
    optional :inventory_settings, :message, 5, "POGOProtos.Settings.InventorySettings"
    optional :minimum_client_version, :string, 6
    optional :gps_settings, :message, 7, "POGOProtos.Settings.GpsSettings"
  end
  add_message "POGOProtos.Settings.InventorySettings" do
    optional :max_pokemon, :int32, 1
    optional :max_bag_items, :int32, 2
    optional :base_pokemon, :int32, 3
    optional :base_bag_items, :int32, 4
    optional :base_eggs, :int32, 5
  end
  add_message "POGOProtos.Settings.LevelSettings" do
    optional :trainer_cp_modifier, :double, 2
    optional :trainer_difficulty_modifier, :double, 3
  end
  add_message "POGOProtos.Settings.DownloadSettingsAction" do
    optional :hash, :string, 1
  end
end

module POGOProtos
  module Settings
    MapSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.MapSettings").msgclass
    FortSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.FortSettings").msgclass
    GpsSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.GpsSettings").msgclass
    GlobalSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.GlobalSettings").msgclass
    InventorySettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.InventorySettings").msgclass
    LevelSettings = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.LevelSettings").msgclass
    DownloadSettingsAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("POGOProtos.Settings.DownloadSettingsAction").msgclass
  end
end
