# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Signature.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Signature" do
    optional :timestamp_since_start, :uint64, 2
    repeated :location_fix, :message, 4, "Signature.LocationFix"
    optional :gps_info, :message, 5, "Signature.AndroidGpsInfo"
    optional :sensor_info, :message, 7, "Signature.SensorInfo"
    optional :device_info, :message, 8, "Signature.DeviceInfo"
    optional :activity_status, :message, 9, "Signature.ActivityStatus"
    optional :location_hash1, :uint32, 10
    optional :location_hash2, :uint32, 20
    optional :unk22, :bytes, 22
    optional :timestamp, :uint64, 23
    repeated :request_hash, :uint64, 24
  end
  add_message "Signature.LocationFix" do
    optional :provider, :string, 1
    optional :timestamp_since_start, :uint64, 2
    optional :latitude, :float, 13
    optional :longitude, :float, 14
    optional :horizontal_accuracy, :float, 20
    optional :altitude, :float, 21
    optional :vertical_accuracy, :float, 22
    optional :provider_status, :uint64, 26
    optional :floor, :uint32, 27
    optional :location_type, :uint64, 28
  end
  add_message "Signature.AndroidGpsInfo" do
    optional :time_to_fix, :uint64, 1
    repeated :satellites_prn, :int32, 2
    repeated :snr, :float, 3
    repeated :azimuth, :float, 4
    repeated :elevation, :float, 5
    repeated :has_almanac, :bool, 6
    repeated :has_ephemeris, :bool, 7
    repeated :used_in_fix, :bool, 8
  end
  add_message "Signature.SensorInfo" do
    optional :timestamp_snapshot, :uint64, 1
    optional :magnetometer_x, :double, 3
    optional :magnetometer_y, :double, 4
    optional :magnetometer_z, :double, 5
    optional :angle_normalized_x, :double, 6
    optional :angle_normalized_y, :double, 7
    optional :angle_normalized_z, :double, 8
    optional :accel_raw_x, :double, 10
    optional :accel_raw_y, :double, 11
    optional :accel_raw_z, :double, 12
    optional :gyroscope_raw_x, :double, 13
    optional :gyroscope_raw_y, :double, 14
    optional :gyroscope_raw_z, :double, 15
    optional :accel_normalized_x, :double, 16
    optional :accel_normalized_y, :double, 17
    optional :accel_normalized_z, :double, 18
    optional :accelerometer_axes, :uint64, 19
  end
  add_message "Signature.DeviceInfo" do
    optional :device_id, :string, 1
    optional :android_board_name, :string, 2
    optional :android_bootloader, :string, 3
    optional :device_brand, :string, 4
    optional :device_model, :string, 5
    optional :device_model_identifier, :string, 6
    optional :device_model_boot, :string, 7
    optional :hardware_manufacturer, :string, 8
    optional :hardware_model, :string, 9
    optional :firmware_brand, :string, 10
    optional :firmware_tags, :string, 12
    optional :firmware_type, :string, 13
    optional :firmware_fingerprint, :string, 14
  end
  add_message "Signature.ActivityStatus" do
    optional :start_time_ms, :uint64, 1
    optional :unknown_status, :bool, 2
    optional :walking, :bool, 3
    optional :running, :bool, 4
    optional :stationary, :bool, 5
    optional :automotive, :bool, 6
    optional :tilting, :bool, 7
    optional :cycling, :bool, 8
    optional :status, :bytes, 9
  end
end

Signature = Google::Protobuf::DescriptorPool.generated_pool.lookup("Signature").msgclass
Signature::LocationFix = Google::Protobuf::DescriptorPool.generated_pool.lookup("Signature.LocationFix").msgclass
Signature::AndroidGpsInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Signature.AndroidGpsInfo").msgclass
Signature::SensorInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Signature.SensorInfo").msgclass
Signature::DeviceInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("Signature.DeviceInfo").msgclass
Signature::ActivityStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("Signature.ActivityStatus").msgclass
